### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by strizzwald** [FRossouw/Web-Assignment-01#8]
https://github.com/FRossouw/Web-Assignment-01/blob/7f57cc8417b099eb85e5536b8171bfb089d9627d/css/body-right-skills-media.css#L1

Consider adding more CSS rules in here to support different devices with smaller viewports

**Comment by FRossouw** [comment]
After the responsiveness issues have been fixed it was noted that the navigation sticky bar is too large for most screens, this needs to be fixed next
